### ISSUE TITLE
Attempt to index global "bdct" 

### ISSUE THREAD

**Issue by pquerner** [blooblahguy/bdCombatText#1]
7x bdCombatText\config.lua:63: attempt to index global 'bdct' (a nil value)
bdCombatText\config.lua:63: in function `callback'
bdCore\config\config.lua:1067: in function <bdCore\config\config.lua:1046>

Locals:
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index global 'bdct' (a nil value)"

**Comment by pquerner** [comment]
Also

6x bdCombatText\config.lua:54: attempt to index global 'bdct' (a nil value)
bdCombatText\config.lua:54: in function `callback'
bdCore\config\config.lua:1067: in function <bdCore\config\config.lua:1046>

Locals:
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index global 'bdct' (a nil value)"

**Comment by gladelynch** [comment]
This issue will be fixed in the next build, but I wouldn't necessarily recommend running this addon yet, it's still really early stages of development. If you wanna test the alpha features then by all means :)

**Comment by pquerner** [comment]
Your addons are spot on. I'll help if I can. :)

2018-01-05 20:49 GMT+01:00 blooblahguy <notifications@github.com>:
